 {
  id: 'evt_3Nk8vFSJDEVNzqXl1q9Hz1JY',
  object: 'event',
  api_version: '2020-08-27',
  created: 1693242719,
  data: {
    object: {
      id: 'pi_3Nk8vFSJDEVNzqXl1dm8LDmN',
      object: 'payment_intent',
      amount: 810000,
      amount_capturable: 0,
      amount_details: [Object],
      amount_received: 810000,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic',
      charges: [Object],
      client_secret: 'pi_3Nk8vFSJDEVNzqXl1dm8LDmN_secret_3536oJz4HIlLX2Bdni8BlDYnQ',
      confirmation_method: 'automatic',
      created: 1693242497,
      currency: 'inr',
      customer: 'cus_OXDPFVqgrxQDla',
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: 'ch_3Nk8vFSJDEVNzqXl1qyYvLVx',
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: 'pm_1Nk8yiSJDEVNzqXlOTlu39uN',
      payment_method_options: [Object],
      payment_method_types: [Array],
      processing: null,
      receipt_email: 'xyz@email.com',
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null
    }
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: 'pi_3Nk8vFSJDEVNzqXl1dm8LDmN-src_1Nk8ykSJDEVNzqXl19w2itC0'
  },
  type: 'payment_intent.succeeded'
}
✅ Success: evt_3Nk8vFSJDEVNzqXl1q9Hz1JY
💰 PaymentIntent status: succeeded
e {
  id: 'evt_3Nk8vFSJDEVNzqXl1uxsIEYU',
  object: 'event',
  api_version: '2020-08-27',
  created: 1693242719,
  data: {
    object: {
      id: 'ch_3Nk8vFSJDEVNzqXl1qyYvLVx',
      object: 'charge',
      amount: 810000,
      amount_captured: 810000,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_3Nk8vFSJDEVNzqXl1gjS1X5J',
      billing_details: [Object],
      calculated_statement_descriptor: 'KYGOSKYRUS CORPORATION',
      captured: true,
      created: 1693242718,
      currency: 'inr',
      customer: 'cus_OXDPFVqgrxQDla',
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: [Object],
      paid: true,
      payment_intent: 'pi_3Nk8vFSJDEVNzqXl1dm8LDmN',
      payment_method: 'pm_1Nk8yiSJDEVNzqXlOTlu39uN',
      payment_method_details: [Object],
      receipt_email: 'xyz@email.com',
      receipt_number: null,
      receipt_url: 'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xSmh2a3BTSkRFVk56cVhsKN-qs6cGMgaFo2mea4A6LBb0ZF91YGYXUG77y1HC3iLPK5Z8pMzdKW_gDaaiiY5w7VLfuxN74z8huAYG',
      refunded: false,
      refunds: [Object],
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null
    }
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: 'pi_3Nk8vFSJDEVNzqXl1dm8LDmN-src_1Nk8ykSJDEVNzqXl19w2itC0'
  },
  type: 'charge.succeeded'
}
✅ Success: evt_3Nk8vFSJDEVNzqXl1uxsIEYU
💵 Charge id: ch_3Nk8vFSJDEVNzqXl1qyYvLVx
